name: test-era5
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - xarray
  - cartopy
  - nc-time-axis
  - jupyter
  - arraylake
  - dask
  - dask-cloudprovider
  - awscli
  - pip
  - pip:
    - pcodec
